#### Step1: Data Load

In [1]:
import pandas as pd
data = pd.read_csv('weight-height.csv')

In [2]:
data.shape

(10000, 3)

In [ ]:
data.head()

In [56]:
data.Gender = [1 if g=="Male" else 0 for g in data.Gender]
data.head()

Gender     Height      Weight
0       0  73.847017  241.893563
1       0  68.781904  162.310473
2       0  74.110105  212.740856
3       0  71.730978  220.042470
4       0  69.881796  206.349801

#### Step2: Separate input data and output
       Data and Labels 

In [57]:
X = data[['Height']]
y = data[['Weight']]

#### Step3: Split Data Training data and Testing Data

In [58]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test   = train_test_split(X,y,random_state=0, test_size=.40)

In [23]:
X_train

Height
7809  64.494318
5279  58.987139
3279  65.682365
8984  62.935048
8466  62.218599
...         ...
9225  60.421255
4859  66.730755
3264  67.467086
9845  62.127480
2732  70.597025

[6000 rows x 1 columns]

In [6]:
import random

In [13]:
random.seed(5566)
random.randint(1,100)

85

# Step:4 Model Selection

In [24]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()

# Step:5 Model Training (Fit Karna)

In [1]:
# supervised learning data+ans
model.fit(X_train,y_train)

NameError: name 'model' is not defined

In [26]:
model.coef_

array([[7.71316805]])

In [27]:
model.intercept_

array([-350.4837037])

# Step6: Prediction on Training Data

In [28]:
y_pred_train = model.predict(X_train)

In [32]:
y_train.values.reshape(6000,)

array([141.8754655, 100.743008 , 186.2707727, ..., 162.4759573,
       136.7830224, 188.4506741])

In [34]:
y_pred_train.reshape(6000,)

array([146.97181036, 104.4940115 , 156.13541212, ..., 169.9012675 ,
       128.71599066, 194.04300997])

In [35]:
pd.DataFrame({"y_train":y_train.values.reshape(6000,), "y_pred":y_pred_train.reshape(6000,) })

y_train      y_pred
0     141.875465  146.971810
1     100.743008  104.494011
2     186.270773  156.135412
3     124.460003  134.944897
4     130.012336  129.418808
...          ...         ...
5995   97.263881  115.555590
5996  174.156893  164.221820
5997  162.475957  169.901267
5998  136.783022  128.715991
5999  188.450674  194.043010

[6000 rows x 2 columns]

In [36]:
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error

In [37]:
r2_score(y_train,y_pred_train)

0.8570169896550387

In [38]:
mean_absolute_error(y_train,y_pred_train)

9.67884817077144

# Step7: Prediction on Test  Data 

In [41]:
y_pred_test = model.predict(X_test)

In [42]:
r2_score(y_test,y_pred_test)

0.8523953836639468

In [43]:
mean_absolute_error(y_test,y_pred_test)

9.848520352275886

In [49]:
def predict1_weight(height):
   return  model.predict(height)*.453592

In [52]:
height = float(input("Enter you height in feet"))
print(f"Your predicted weight is {predict1_weight([[height*12]])} kgs")

Enter you height in feet 5.11


Your predicted weight is [[55.55946843]] kgs


C:\Users\Nasir Hussain\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


In [55]:
data.Gender = [1 if g=="Male" else 0 for g in data.Gender]
data

Gender     Height      Weight
0          1  73.847017  241.893563
1          1  68.781904  162.310473
2          1  74.110105  212.740856
3          1  71.730978  220.042470
4          1  69.881796  206.349801
...      ...        ...         ...
9995       0  66.172652  136.777454
9996       0  67.067155  170.867906
9997       0  63.867992  128.475319
9998       0  69.034243  163.852461
9999       0  61.944246  113.649103

[10000 rows x 3 columns]

In [77]:
X = data[['Gender', 'Height']]
X

Gender     Height
0          0  73.847017
1          0  68.781904
2          0  74.110105
3          0  71.730978
4          0  69.881796
...      ...        ...
9995       0  66.172652
9996       0  67.067155
9997       0  63.867992
9998       0  69.034243
9999       0  61.944246

[10000 rows x 2 columns]

In [84]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test   = train_test_split(X,y,random_state=13230, test_size=.40)

In [85]:
mlr = LinearRegression()

In [86]:
mlr.fit(X_train, y_train)

LinearRegression()

In [87]:
y_pred_train = mlr.predict(X_train)

In [88]:
r2_score(y_train,y_pred_train)

0.8578885186182372