In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import sklearn

#### Step1: Data Load

In [3]:
data = pd.read_csv("advertising.csv")

In [4]:
data.shape

(200, 4)

In [5]:
data.head()

TV  Radio  Newspaper  Sales
0  230.1   37.8       69.2   22.1
1   44.5   39.3       45.1   10.4
2   17.2   45.9       69.3   12.0
3  151.5   41.3       58.5   16.5
4  180.8   10.8       58.4   17.9

#### Step2: Separate input data and output
       Data and Labels 

In [6]:
X = data[['TV', 'Radio', 'Newspaper']]
y = data[['Sales']]

In [9]:
X

TV  Radio  Newspaper
0    230.1   37.8       69.2
1     44.5   39.3       45.1
2     17.2   45.9       69.3
3    151.5   41.3       58.5
4    180.8   10.8       58.4
..     ...    ...        ...
195   38.2    3.7       13.8
196   94.2    4.9        8.1
197  177.0    9.3        6.4
198  283.6   42.0       66.2
199  232.1    8.6        8.7

[200 rows x 3 columns]

In [10]:
y

Sales
0     22.1
1     10.4
2     12.0
3     16.5
4     17.9
..     ...
195    7.6
196   14.0
197   14.8
198   25.5
199   18.4

[200 rows x 1 columns]

#### Step3: Split Data Training data and Testing Data

In [11]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test   = train_test_split(X,y,random_state=1234, test_size=.20)

In [12]:
X_train

TV  Radio  Newspaper
146  240.1    7.3        8.7
32    97.2    1.5       30.0
43   206.9    8.4       26.4
99   135.2   41.7       45.9
88    88.3   25.5       73.4
..     ...    ...        ...
152  197.6   23.3       14.2
116  139.2   14.3       25.6
53   182.6   46.2       58.7
38    43.1   26.7       35.1
47   239.9   41.5       18.5

[160 rows x 3 columns]

In [13]:
X_test

TV  Radio  Newspaper
197  177.0    9.3        6.4
157  149.8    1.3       24.3
31   112.9   17.4       38.6
48   227.2   15.8       49.9
63   102.7   29.6        8.4
59   210.7   29.5        9.3
5      8.7   48.9       75.0
7    120.2   19.6       11.6
117   76.4    0.8       14.8
108   13.1    0.4       25.6
141  193.7   35.4       75.6
54   262.7   28.8       15.9
102  280.2   10.1       21.4
131  265.2    2.9       43.0
172   19.6   20.1       17.0
155    4.1   11.6        5.7
126    7.8   38.9       50.6
29    70.6   16.0       40.8
74   213.4   24.6       13.1
65    69.0    9.3        0.9
137  273.7   28.9       59.7
101  296.4   36.3      100.9
189   18.7   12.1       23.4
51   100.4    9.6        3.6
92   217.7   33.5       59.0
111  241.7   38.0       23.2
9    199.8    2.6       21.2
136   25.6   39.0        9.3
125   87.2   11.8       25.9
40   202.5   22.3       31.6
6     57.5   32.8       23.5
193  166.8   42.0        3.6
150  280.7   13.9       37.0
145  140.3    1.9        9.0
123  123.1   34.6       12.4
162  188.4   18.1       25.6
93   250.9   36.5       72.3
183  287.6   43.0       71.8
170   50.0   11.6       18.4
58   210.8   49.6       37.7

In [14]:
y_train

Sales
146   18.2
32    13.2
43    17.9
99    17.2
88    12.9
..     ...
152   16.6
116   12.2
53    21.2
38    10.1
47    23.2

[160 rows x 1 columns]

In [15]:
y_test

Sales
197   14.8
157   10.1
31    11.9
48    19.8
63    14.0
59    18.4
5      7.2
7     13.2
117    9.4
108    5.3
141   19.2
54    20.2
102   19.8
131   17.7
172    7.6
155    3.2
126    6.6
29    10.5
74    17.0
65    11.3
137   20.8
101   23.8
189    6.7
51    10.7
92    19.4
111   21.8
9     15.6
136    9.5
125   10.6
40    16.6
6     11.8
193   19.6
150   16.1
145   10.3
123   15.2
162   19.9
93    22.2
183   26.2
170    8.4
58    23.8

#### Step:4 Model Selection

In [16]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()

#### Step:5 Model Training (Fit Karna)

In [17]:
# supervised learning data+ans
model.fit(X_train,y_train)

LinearRegression()

In [18]:
model.coef_

array([[0.05473391, 0.10077489, 0.00396569]])

In [19]:
model.intercept_

array([4.75099902])

#### Step6: Prediction on Training Data

In [22]:
y_pred_train = model.predict(X_train)

In [24]:
y_train.values.reshape(160,)

array([18.2, 13.2, 17.9, 17.2, 12.9, 21.5, 17. , 10.8, 16.7, 16.7, 24.4,
       17.4, 11.9,  5.7, 16.9, 14.2, 16.4, 20.7, 17.3, 20.9, 20.5, 11. ,
       16.6,  9.7,  1.6, 24.2, 11.5,  7.3, 18. , 20.9, 16.9,  8.7, 17.3,
       17.8, 13.6, 20.7, 14.6, 25.4, 17.6, 13.2, 10.6, 13.4, 11. ,  9.6,
       10.1, 17.1, 25.4, 22.4,  9.7,  8.5,  4.8,  6.6,  5.5,  5.6,  7.2,
       18.4, 10.3, 17.2, 11. ,  9.2, 10.8, 20. , 18. , 10.4, 10.9, 20.1,
       16. , 22.6, 12.9,  9.7, 18.9, 12.4, 17.5, 16. , 17.4, 14. , 25.4,
       22.1, 15. , 11.6, 15.5, 20.7,  7. , 16.8,  5.9,  5.3, 13.3, 23.7,
        7.6, 19.7, 11.3, 17.9, 18.9, 12.6, 17.6, 22.6, 12.3, 19.6, 11.6,
       25.5, 19.8, 20.2, 20.2, 11.3, 18.4, 12. , 18.3,  8.8, 17.1, 12.5,
       16.1, 21.7, 16.7, 20.9, 16.5, 16.7, 14. , 13.7, 16. , 17.3, 15.3,
       11.9,  8.1, 19. , 12. , 12.6, 10.9, 14.6, 12. , 16.5, 17.2,  8.7,
       24.7, 20.7,  8. , 11.9, 14.7,  6.9, 16.4, 27. , 11.9, 11.8, 22.3,
       17.1, 15.5, 15.9, 15. , 19.7,  7.3, 17.5, 21

In [25]:
y_pred_train.reshape(160,)

array([18.66276778, 10.34126748, 17.02664714, 16.53536081, 12.4448438 ,
       21.15644462, 19.57058564, 10.92073978, 14.73445112, 17.55464266,
       24.36509075, 18.93682852,  9.99557176,  7.96016874, 17.08331696,
       14.27483165, 16.13836967, 21.26621204, 18.17506307, 19.66636447,
       17.07481581,  8.9629038 , 17.31511818,  9.73770068,  8.81449982,
       23.57297916, 12.08349484,  6.59841865, 19.70811591, 21.82033987,
       18.26502449,  8.5192422 , 16.55604477, 21.1090306 , 13.12045908,
       23.61947622, 13.88427134, 23.79324685, 20.90793983, 14.20646514,
       10.79987667, 13.87711788, 11.96770598,  9.79592311,  9.87928983,
       19.14739303, 23.17593416, 20.46275103,  9.50325694,  8.88644885,
        5.43730355,  7.51366978,  8.14651027,  7.27250528,  7.34565127,
       18.16033009, 12.70349327, 16.67093431, 12.53210915,  9.85220322,
       11.07783718, 21.40544245, 17.43785449, 11.32596333, 10.93930709,
       20.31585088, 16.35438753, 20.95477009, 13.95092498,  9.39

In [26]:
pd.DataFrame({"y_train":y_train.values.reshape(160,), "y_pred":y_pred_train.reshape(160,) })

y_train     y_pred
0       18.2  18.662768
1       13.2  10.341267
2       17.9  17.026647
3       17.2  16.535361
4       12.9  12.444844
..       ...        ...
155     16.6  17.970786
156     12.2  13.912561
157     21.2  19.633996
158     10.1   9.939915
159     23.2  22.137186

[160 rows x 2 columns]

In [27]:
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error

R-Squared values range from 0 to 1. An R-Squared value of 0 means that the model explains or predicts 0% of the relationship between the dependent and independent variables. A value of 1 indicates that the model predicts 100% of the relationship, and a value of 0.5 indicates that the model predicts 50%, and so on.

In [28]:
r2_score(y_train,y_pred_train)

0.8990871038598716

In [29]:
mean_absolute_error(y_train,y_pred_train)

1.2371761601789153

#### Step7: Prediction on Test  Data 

In [30]:
y_pred_test = model.predict(X_test)

In [31]:
r2_score(y_test,y_pred_test)

0.9086637457300811

In [39]:
mean_absolute_error(y_test,y_pred_test)

1.282536129603624

In [37]:
def predict_sales(data):
    return model.predict(data)

In [40]:
tv_sold = float(input("Enter No of TV Sold"))
radio_sold = float(input("Enter No of Radio Sold"))
news_paper_sold = float(input("Enter No of Newspaper Sold"))

predicted_sales = predict_sales([[tv_sold, radio_sold, news_paper_sold]])
print(predicted_sales)

Enter No of TV Sold 44.5
Enter No of Radio Sold 39.3
Enter No of Newspaper Sold 45.1


[[11.32596333]]


C:\Users\zeesh\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


#### Normalization

In [42]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
#scaler.fit(X)
scaled_x = scaler.fit_transform(X)
columns = scaler.feature_names_in_

In [43]:
X = pd.DataFrame(data=scaled_x, columns=columns)

In [45]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test   = train_test_split(X,y,random_state=1234, test_size=.20)

In [46]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()

In [47]:
# supervised learning data+ans
model.fit(X_train,y_train)

LinearRegression()

In [48]:
model.coef_

array([[16.18481574,  4.9984345 ,  0.45089841]])

In [49]:
model.intercept_

array([4.79050245])

#### Prediction on Training Data

In [50]:
y_pred_train = model.predict(X_train)

In [51]:
y_train.values.reshape(160,)

array([18.2, 13.2, 17.9, 17.2, 12.9, 21.5, 17. , 10.8, 16.7, 16.7, 24.4,
       17.4, 11.9,  5.7, 16.9, 14.2, 16.4, 20.7, 17.3, 20.9, 20.5, 11. ,
       16.6,  9.7,  1.6, 24.2, 11.5,  7.3, 18. , 20.9, 16.9,  8.7, 17.3,
       17.8, 13.6, 20.7, 14.6, 25.4, 17.6, 13.2, 10.6, 13.4, 11. ,  9.6,
       10.1, 17.1, 25.4, 22.4,  9.7,  8.5,  4.8,  6.6,  5.5,  5.6,  7.2,
       18.4, 10.3, 17.2, 11. ,  9.2, 10.8, 20. , 18. , 10.4, 10.9, 20.1,
       16. , 22.6, 12.9,  9.7, 18.9, 12.4, 17.5, 16. , 17.4, 14. , 25.4,
       22.1, 15. , 11.6, 15.5, 20.7,  7. , 16.8,  5.9,  5.3, 13.3, 23.7,
        7.6, 19.7, 11.3, 17.9, 18.9, 12.6, 17.6, 22.6, 12.3, 19.6, 11.6,
       25.5, 19.8, 20.2, 20.2, 11.3, 18.4, 12. , 18.3,  8.8, 17.1, 12.5,
       16.1, 21.7, 16.7, 20.9, 16.5, 16.7, 14. , 13.7, 16. , 17.3, 15.3,
       11.9,  8.1, 19. , 12. , 12.6, 10.9, 14.6, 12. , 16.5, 17.2,  8.7,
       24.7, 20.7,  8. , 11.9, 14.7,  6.9, 16.4, 27. , 11.9, 11.8, 22.3,
       17.1, 15.5, 15.9, 15. , 19.7,  7.3, 17.5, 21

In [52]:
y_pred_train.reshape(160,)

array([18.66276778, 10.34126748, 17.02664714, 16.53536081, 12.4448438 ,
       21.15644462, 19.57058564, 10.92073978, 14.73445112, 17.55464266,
       24.36509075, 18.93682852,  9.99557176,  7.96016874, 17.08331696,
       14.27483165, 16.13836967, 21.26621204, 18.17506307, 19.66636447,
       17.07481581,  8.9629038 , 17.31511818,  9.73770068,  8.81449982,
       23.57297916, 12.08349484,  6.59841865, 19.70811591, 21.82033987,
       18.26502449,  8.5192422 , 16.55604477, 21.1090306 , 13.12045908,
       23.61947622, 13.88427134, 23.79324685, 20.90793983, 14.20646514,
       10.79987667, 13.87711788, 11.96770598,  9.79592311,  9.87928983,
       19.14739303, 23.17593416, 20.46275103,  9.50325694,  8.88644885,
        5.43730355,  7.51366978,  8.14651027,  7.27250528,  7.34565127,
       18.16033009, 12.70349327, 16.67093431, 12.53210915,  9.85220322,
       11.07783718, 21.40544245, 17.43785449, 11.32596333, 10.93930709,
       20.31585088, 16.35438753, 20.95477009, 13.95092498,  9.39

In [53]:
pd.DataFrame({"y_train":y_train.values.reshape(160,), "y_pred":y_pred_train.reshape(160,) })

y_train     y_pred
0       18.2  18.662768
1       13.2  10.341267
2       17.9  17.026647
3       17.2  16.535361
4       12.9  12.444844
..       ...        ...
155     16.6  17.970786
156     12.2  13.912561
157     21.2  19.633996
158     10.1   9.939915
159     23.2  22.137186

[160 rows x 2 columns]

In [54]:
r2_score(y_train,y_pred_train)

0.8990871038598716

In [55]:
mean_absolute_error(y_train,y_pred_train)

1.2371761601789153

#### Prediction on Testing Data

In [56]:
y_pred_test = model.predict(X_test)

In [58]:
y_test.values.reshape(40,)

array([14.8, 10.1, 11.9, 19.8, 14. , 18.4,  7.2, 13.2,  9.4,  5.3, 19.2,
       20.2, 19.8, 17.7,  7.6,  3.2,  6.6, 10.5, 17. , 11.3, 20.8, 23.8,
        6.7, 10.7, 19.4, 21.8, 15.6,  9.5, 10.6, 16.6, 11.8, 19.6, 16.1,
       10.3, 15.2, 19.9, 22.2, 26.2,  8.4, 23.8])

In [60]:
y_pred_test.reshape(40,)

array([15.40148707, 13.17751151, 12.83701542, 18.9766732 , 13.38841954,
       19.29317292, 10.45250245, 13.35120418,  9.07198142,  5.60984467,
       19.22019331, 22.09496709, 21.19013127, 19.72920229,  7.91677547,
        6.16700114,  9.29873033, 10.3894109 , 18.96222711,  9.46841405,
       22.88081454, 25.0323946 ,  7.08669623, 11.22799849, 20.27650437,
       21.90163356, 16.03292049, 10.11928853, 10.81565048, 18.20721048,
       11.29680852, 18.12743619, 21.66230749, 12.65732936, 15.02472839,
       16.98841377, 22.4487383 , 25.11052655,  8.72965159, 21.43684704])

In [62]:
pd.DataFrame({"y_test":y_test.values.reshape(40,), "y_pred_test":y_pred_test.reshape(40,) })

y_test  y_pred_test
0     14.8    15.401487
1     10.1    13.177512
2     11.9    12.837015
3     19.8    18.976673
4     14.0    13.388420
5     18.4    19.293173
6      7.2    10.452502
7     13.2    13.351204
8      9.4     9.071981
9      5.3     5.609845
10    19.2    19.220193
11    20.2    22.094967
12    19.8    21.190131
13    17.7    19.729202
14     7.6     7.916775
15     3.2     6.167001
16     6.6     9.298730
17    10.5    10.389411
18    17.0    18.962227
19    11.3     9.468414
20    20.8    22.880815
21    23.8    25.032395
22     6.7     7.086696
23    10.7    11.227998
24    19.4    20.276504
25    21.8    21.901634
26    15.6    16.032920
27     9.5    10.119289
28    10.6    10.815650
29    16.6    18.207210
30    11.8    11.296809
31    19.6    18.127436
32    16.1    21.662307
33    10.3    12.657329
34    15.2    15.024728
35    19.9    16.988414
36    22.2    22.448738
37    26.2    25.110527
38     8.4     8.729652
39    23.8    21.436847

In [63]:
r2_score(y_test,y_pred_test)

0.908663745730081

In [64]:
mean_absolute_error(y_test,y_pred_test)

1.2825361296036244

In [65]:
data.corr()

TV     Radio  Newspaper     Sales
TV         1.000000  0.054809   0.056648  0.901208
Radio      0.054809  1.000000   0.354104  0.349631
Newspaper  0.056648  0.354104   1.000000  0.157960
Sales      0.901208  0.349631   0.157960  1.000000