# Numpy
NumPy is a Python library used for working with arrays.

NumPy stands for Numerical Python.

---
### Why is NumPy Faster Than Lists?
NumPy arrays are stored at one continuous place in memory unlike lists, so processes can access and manipulate them very efficiently.

This behavior is called locality of reference in computer science.

This is the main reason why NumPy is faster than lists. Also it is optimized to work with latest CPU architectures.

---
### Which Language is NumPy written in?
NumPy is a Python library and is written partially in Python, but most of the parts that require fast computation are written in C or C++.

In [2]:
# Import NumPy
# make alias with as to short numpy to np
import numpy as np

In [3]:
# Now NumPy is imported and ready to use.
arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


In [4]:
# Checking NumPy Version
print(np.__version__)

1.26.4


#### Create a NumPy ndarray Object
NumPy is used to work with arrays. The array object in NumPy is called ndarray.

We can create a NumPy ndarray object by using the __array()__ function. 

To create an __ndarray__, we can pass a _list_, _tuple_ or any array-like object into the __array()__ method, and it will be converted into an _ndarray_

In [9]:
np.array([1,2,3,4,5,6,7,8,9,0])

array([1, 2, 3, 4, 5, 6, 7, 8, 9, 0])

In [11]:
np.array((1,2,3,4,5,6,7,8,9,0))

array([1, 2, 3, 4, 5, 6, 7, 8, 9, 0])

#### 0-D Arrays
0-D arrays, or __Scalars__, are the elements in an array. Each value in an array is a 0-D array.

In [14]:
arr = np.array(42)
print(arr)

42


#### 1-D Arrays
An array that has 0-D arrays as its elements is called __uni-dimensional__ or _1-D array_.

These are the most common and basic arrays.

In [17]:
arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


#### 2-D Arrays
An array that has 1-D arrays as its elements is called a __2-D array__.

These are often used to represent __matrix__ or __2nd order tensors__.

In [20]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)

[[1 2 3]
 [4 5 6]]


#### 3-D arrays
An array that has 2-D arrays (matrices) as its elements is called __3-D array__.

These are often used to represent a __3rd order tensor__.

In [23]:
arr = np.array([
    [
        [1, 2, 3], 
        [4, 5, 6]
    ], 
    [
        [1, 2, 3], 
        [4, 5, 6]
    ]
])
print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [25]:
# Check Number of Dimensions?
# NumPy Arrays provides the ndim attribute that returns an integer that tells us how many dimensions the array have.

a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [27]:
# Higher Dimensional Arrays
# An array can have any number of dimensions.
# When the array is created, you can define the number of dimensions by using the ndmin argument.

arr = np.array([1, 2, 3, 4], ndmin=5)
print(arr)
print('number of dimensions :', arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions : 5


### Access Array Elements

In [30]:
# Access Array Elements
# Array indexing is the same as accessing an array element.
# You can access an array element by referring to its index number.

arr = np.array([1, 2, 3, 4])
print(arr[0])

1


In [32]:
arr = np.array([1, 2, 3, 4])

print(arr[2] + arr[3])

7


In [34]:
# Access 2-D Arrays
# To access elements from 2-D arrays we can use comma separated integers representing the dimension and the index of the element.
# Think of 2-D arrays like a table with rows and columns, where the dimension represents the row and the index represents the column.

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('5th element on 2nd row: ', arr[1, 4])

5th element on 2nd row:  10


In [36]:
# Access 3-D Arrays
# To access elements from 3-D arrays we can use comma separated integers representing the dimensions and the index of the element.

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr)
print(arr[0, 1, 2])

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
6


In [38]:
# Negative Indexing
# Use negative indexing to access an array from the end.
import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('Last element from 2nd dim: ', arr[1, -1])

Last element from 2nd dim:  10


### NumPy Array Slicing

#### Slicing arrays
Slicing in python means taking elements from one given index to another given index.

We pass slice instead of index like this: __[start:end]__.

We can also define the step, like this: __[start:end:step]__.

If we don't pass start its considered __0__

If we don't pass end its considered __length of array__ in that dimension

If we don't pass step its considered __1__

In [42]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[1:5])

[2 3 4 5]


In [44]:
# Slice elements from index 4 to the end of the array:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[4:])

[5 6 7]


In [46]:
# Slice elements from the beginning to index 4 (not included):
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[:4])

[1 2 3 4]


#### Negative Slicing

In [49]:
# Slice from the index 3 from the end to index 1 from the end:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[-3:-1])

[5 6]


#### Step
Use the step value to determine the step of the slicing:

In [52]:
# Return every other element from index 1 to index 5:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[1:5:2])

[2 4]


In [54]:
# Return every other element from the entire array:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[::2])

[1 3 5 7]


In [56]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[::-1])

[7 6 5 4 3 2 1]


#### Slicing 2-D Arrays

In [59]:
# From the second element, slice elements from index 1 to index 4 (not included):
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[1, 1:4])

[7 8 9]


In [61]:
# From both elements, return index 2:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2, 2])

[3 8]


In [63]:
# From both elements, slice index 1 to index 4 (not included), this will return a 2-D array:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2, 1:4])

[[2 3 4]
 [7 8 9]]
